name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: mkdir build && cd build
    - name: cmake
      run: cmake ..
    - name: Build release
      run: make release
    - name: Build and run unit tests
      run: make test
