name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cmake
      run: cmake -S . -B build
    - name: Build release
      run: cd build && make release
    - name: Build and run unit tests
      run: cd build && make test
