name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cmake
      run: cmake -S . -B build
    - name: Build release
      run: cd build && make release
    - name: Build and run unit tests
      run: cd build && make test

  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: clang-format
      uses: jidicula/clang-format-action@v4.13.0
      with:
        clang-format-version: '18'